feat: 🎸 add mdict
ZuodaoTech/everyone-can-use-english pull request #1062
Opened 2024-09-10 11:02 UTC by divisey

2024-09-11 22:49 UTC, an-lee commented
The checks have failed.

```
➤ YN0001: Error: js-mdict@ @divisey/js-mdict isn't supported by any available resolver
    at yg.getResolverByDescriptor (/Users/runner/work/everyone-can-use-english/everyone-can-use-english/.yarn/releases/yarn-4.4.1.cjs:141:1698)
    at yg.bindDescriptor (/Users/runner/work/everyone-can-use-english/everyone-can-use-english/.yarn/releases/yarn-4.4.1.cjs:141:1083)
    at t.preparePackage (/Users/runner/work/everyone-can-use-english/everyone-can-use-english/.yarn/releases/yarn-4.4.1.cjs:210:6173)
    at async Z (/Users/runner/work/everyone-can-use-english/everyone-can-use-english/.yarn/releases/yarn-4.4.1.cjs:210:7587)
    at async Promise.allSettled (index 3)
    at async _c (/Users/runner/work/everyone-can-use-english/everyone-can-use-english/.yarn/releases/yarn-4.4.1.cjs:140:53121)
    at async /Users/runner/work/everyone-can-use-english/everyone-can-use-english/.yarn/releases/yarn-4.4.1.cjs:210:9166
    at async Rt.startProgressPromise (/Users/runner/work/everyone-can-use-english/everyone-can-use-english/.yarn/releases/yarn-4.4.1.cjs:140:138998)
    at async t.resolveEverything (/Users/runner/work/everyone-can-use-english/everyone-can-use-english/.yarn/releases/yarn-4.4.1.cjs:210:7138)
    at async /Users/runner/work/everyone-can-use-english/everyone-can-use-english/.yarn/releases/yarn-4.4.1.cjs:213:[26](https://github.com/ZuodaoTech/everyone-can-use-english/actions/runs/10791128415/job/29927869857?pr=1062#step:5:28)45
```

2024-09-11 22:51 UTC, an-lee requested changes

2024-09-11 22:51 UTC, an-lee commented on enjoy/package.json
> +    "js-mdict": " @divisey/js-mdict",
Is this package in private?

2024-09-12 02:31 UTC, divisey commented on enjoy/package.json
> +    "js-mdict": " @divisey/js-mdict",
it's a grammar issue

2024-09-12 02:40 UTC, merged